### ISSUE TITLE
Implement clang-format into beautifier-clang-format

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/beautifier-clang-format#1]
Time to implement the actual clang-format executable beautifier into this.

**Comment by szeck87** [comment]
@Glavin001 clang-format is different in that we can't pass a config file directly into the command.  The only options are to pass `-style=file` in which clang-format will look for the file on its own.  Or `-style="{key: value, ...}"` to pass the options in directly.

**Comment by Glavin001** [comment]
For some beautifiers like this I had to create a temporary file for config file and use it and then delete it afterwards.

**Comment by szeck87** [comment]
Closed with #2.
